language: c
os: linux

dist: trusty

before_script:
  - npm install -g gulp
  - npm install
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - gulp && /snap/bin/hugo

branches:
  only:
    - master

notifications:
  email: false
