language: objective-c

before_script:
  - brew update && brew upgrade
  - npm install -g gulp
  - npm install
  - brew install hugo
script:
  - gulp && hugo --baseUrl='http://takuti.me/'
branches:
  only:
    - master
