language: c
os: osx

before_script:
  - npm install -g gulp
  - npm install
  - brew update && brew install hugo

script:
  - gulp && hugo --baseUrl='https://takuti.me/'

branches:
  only:
    - master

notifications:
  email: false
