language: c
os: osx

before_script:
  - npm install -g gulp
  - npm install
  - brew update && brew install hugo

script:
  - rake
  - ls public

branches:
  only:
    - master

notifications:
  email: false
