language: c
os: linux

dist: trusty

before_script:
  - npm install -g gulp-cli
  - npm install
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - npx gulp

branches:
  only:
    - master

notifications:
  email: false
