language: c
os: linux

dist: trusty

before_script:
  - npm install -g gulp
  - npm install
  - sudo apt-get update -qq && sudo apt-get install -y hugo

script:
  - gulp && hugo

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  repo: takuti/takuti.github.io
  target_branch: master
  fqdn: takuti.me
