name: takuti.me
url: http://takuti.me/

baseurl: http://takuti.me

markdown: redcarpet
redcarpet:
  extensions: [no_intra_emphasis,tables,autolink,strikethrough]
highlighter: nil # not use pygments because of using google-code-prettify

exclude: ['Rakefile']
include: ['.htaccess']

permalink: /note/:title/

