name: takuti.me
url: http://takuti.me/

markdown: kramdown
highlighter: nil # not use pygments because of using google-code-prettify

exclude: ['Rakefile']
include: ['.htaccess']

permalink: /note/:title/

