[build]
  publish = "public/"
  command = "npm run build"

[build.environment]
  GIT_LFS_ENABLED = "true"
  HUGO_VERSION = "0.88.1"
  TZ = "America/Vancouver"

# Asset Optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
