[build]
  publish = "public/"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.88.1"
  TZ = "America/Vancouver"
  # The following variables should be set in the Netlify UI:
  # GIT_LFS_ENABLED = "true"
  # GIT_LFS_FETCH_INCLUDE = "*.jpg,*.png,*.jpeg,*.svg,*.gif,*.pdf,*.mp4,*.bmp,*.webp,*.mp3"
  # ^ adding mp3 to the default
  # https://github.com/netlify/build-image/blob/focal/buildbot-git-config#L2

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/cal"
  to = "https://calendly.com/takuti"

[[redirects]]
  from = "/cv"
  to = "https://takuti.github.io/cv/"

[[redirects]]
  from = "/cv/Takuya_Kitazawa.pdf"
  to = "https://takuti.github.io/cv/Takuya_Kitazawa.pdf"

# https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-country-or-language
# https://www.netlify.com/blog/2021/11/05/how-to-internationalize-sites-with-country-based-redirects/
# [[redirects]]
#   from = "/"
#   to = "/ja"
#   status = 302
#   force = true
#   conditions = {Language = ["ja"]}
